services:
  postgres:
    image: ghcr.io/ferretdb/postgres-documentdb:17-0.103.0-ferretdb-2.2.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ferretdb}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-securepassword123}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ferretdb-network

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:2.3.1
    ports:
      - '27017:27017'
    environment:
      FERRETDB_POSTGRESQL_URL: 'postgres://${POSTGRES_USER:-ferretdb}:${POSTGRES_PASSWORD:-securepassword123}@postgres:5432/${POSTGRES_DB:-postgres}'
    depends_on:
      - postgres
    networks:
      - ferretdb-network

volumes:
  postgres-data:

networks:
  ferretdb-network:
    driver: bridge
